"""Ports implemented by dp; service can use fakes without importing infrastructure."""
from pathlib import Path
from typing import BinaryIO, Protocol
from .models import Course, Document, Message, Note, ParsedDocument

class LibraryRepository(Protocol):
    def create_course(self, course: Course) -> dict: ...
    def courses(self) -> list[dict]: ...
    def course(self, course_id: str) -> dict: ...
    def cancel_pending(self, course_id: str) -> None: ...
    def documents(self, course_id: str) -> list[dict]: ...
    def document(self, document_id: str) -> dict: ...
    def add_document(self, document: Document, pages: list[str]) -> dict: ...
    def page_text(self, document_id: str, start: int, end: int) -> str: ...
    def delete_document(self, document_id: str) -> None: ...
    def messages(self, course_id: str) -> list[dict]: ...
    def add_messages(self, messages: list[Message]) -> None: ...
    def notes(self, course_id: str, document_id: str | None = None) -> list[dict]: ...
    def add_note(self, note: Note) -> dict: ...
    def delete_note(self, note_id: str) -> None: ...

class FileStore(Protocol):
    def stage(self, stream: BinaryIO, limit: int) -> tuple[Path, int, str]: ...
    def commit(self, staged: Path, document: dict) -> None: ...
    def path(self, document: dict) -> Path: ...
    def discard(self, path: Path) -> None: ...
    def quarantine(self, document: dict) -> Path | None: ...
    def restore(self, staged: Path, document: dict) -> None: ...

class DocumentParser(Protocol):
    def parse(self, path: Path, extension: str) -> ParsedDocument: ...

class AnswerProvider(Protocol):
    def answer(self, action: str, selected: str, question: str, context: str) -> str: ...
